### ISSUE TITLE
FHIRObject.__setattr__ - добавить обработку присваивания None

### ISSUE THREAD

**Issue by abookin** [blanebf/fhir_tools#2]
Добавить возможность удаления параметра/атрибута при записи в него None, если параметр существовал. И ничего не делать, если параметра не было.
None не существует в системе Fhir, по сути это отсутствие атрибута.
Позволит проще выстроить работу с библиотекой.

Мое видение решения проблемы:

    def __setattr__(self, name, value):
        if name in self._fhir_fields:
            if value is None:
                try:
                    delattr(self, name)
                except AttributeError:
                    pass
            else:
                self[name] = value
        else:
            raise AttributeError(name)

Жаль не Python 3... там есть suppress exception

**Comment by abookin** [comment]
Аналогичное поведение стоит сделать и для пустого списка.
Это заметно упростит жизнь, при этом не поломав логику. Пустые массивы, как и не заданные переменные в Fhir json не отображаются

    def set(self, name, value):
        if name in self._fhir_fields:
            if value is None or (isinstance(value, list) and not value):
                try:
                    self.__delattr__(name)
                except (AttributeError, KeyError):
                    pass
            else:
                self[name] = value
        else:
            raise AttributeError(name)

**Comment by blanebf** [comment]
done
