### ISSUE TITLE
Адаптация Fhir Complex типов к SQL синтаксису

### ISSUE THREAD

**Issue by abookin** [blanebf/fhir_tools#4]
Механизм адаптации аналогичен PEP 246. Замечу, что этот гайдлайн уже отменен, но все еще используется peewee.
Суть в адаптации объекта к определенному протоколу.
Объект FHIRObject должен поддерживать методы:
__conform__ -  подтверждение поддержки протокола
getquoted - возвращает параметр в виде валидной SQL строки для вставки в тело запроса

Предлагаю такой код:

    def __conform__(self, proto):
        if proto is _ext.ISQLQuote:
            return self

    def getquoted(self):
        return Json(self)

**Comment by blanebf** [comment]
rejected
