### ISSUE TITLE
FHIRObject.__init__ не кидает исключение при неверном атрибуте, нет проверки на None

### ISSUE THREAD

**Issue by abookin** [blanebf/fhir_tools#5]
Думаю, что стоит сделать логику инициализации объекта аналогичной __setatr__.

Предложение по изменению кода:

    def __init__(self, **kwargs):
        for name, value in six.iteritems(kwargs):
            self.set(name, value)

    def set(self, name, value):
        if name in self._fhir_fields:
            if value is None:
                try:
                    delattr(self, name)
                except AttributeError:
                    pass
            else:
                self[name] = value
        else:
            raise AttributeError(name)

    def __setattr__(self, name, value):
        self.set(name, value)

**Comment by blanebf** [comment]
Done in a way
